import UIKit

/*
 1 - Elimizde sadece harflerden oluşan (noktalama işareti veya sayılar yok) uzun stringler olsun. Bu stringler içinde bazı harflerin tekrar edeceğini düşünün. Mesela 'a' harfi 20 farklı yerde geçiyor olabilir. Bir fonksiyon ile verilen parametre değerine eşit ve daha fazla bulunan harfleri siliniz.Sonra geriye kalan stringi ekrana yazdırınız.
  
  Örnek string: "aaba kouq bux"
  Tekrar sayısı 2 verildiğinde : a,b,u silinmeli ve ekrana "koq x" yazılmalı
  Tekrar sayısı 3 verildiğinde : a silinmeli ve ekrana "b kouq bux"
  tekrar sayısı 4 verildiğinde : hiç bir harf silinmeyip aynı string yazılmalı

 */

func removeRecurringCharacters(from string: String, withThreshold threshold: Int) -> String {
    var charCounts = [Character: Int]()
    
    // stringdeki karakterlerin her birinden kac tane oldugunu yaz
    for char in string {
        if char.isLetter {
            charCounts[char, default: 0] += 1
        }
    }
    
    // thresholdu aşan karakteri sil
    var newString = ""
    for char in string {
        if let count = charCounts[char], char.isLetter, count < threshold {
            newString.append(char)
        } else if !char.isLetter {
            newString.append(char)
        }
    }
    
    return newString
}

let inputString = "aaba kouq bux"
let threshold = 2
//print(removeRecurringCharacters(from: inputString, withThreshold: threshold))



/*
 
 2- Elimizde uzun bir cümle olsun. Bazı kelimelerin tekrar ettiği bir cümle düşünün. İstediğimiz ise,
 hangi kelimeden kaç tane kullanıldığını bulmak.
 String = "Merhaba nasılsınız iyiyim siz nasılsınız bende iyiyim"
 Merhaba 1 kere, nasılsınız 2 kere iyiyim 2 kere 
 
 */

func findWordsCount(in string: String) -> [String: Int] {
    
    var wordCounts = [String: Int]()
    
    //cumleyi kelimelere ayirma
    let words = inputSentence.components(separatedBy: " ")
    
    //her kelimenin kac kez tekrar ettigini say
    for word in words {
        wordCounts[word, default: 0] += 1
    }
    return wordCounts
}

let inputSentence = "Merhaba nasılsınız iyiyim siz nasılsınız ben de iyiyim"
let wordOccurrences = findWordsCount(in: inputSentence)
//print(wordOccurrences)


/*
 If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
 */

func sumOfMultiples () -> Int{
    
    var sumOfMult = 0
    let count: Int = 16

    
    for number in 1..<count{
        if number % 3 == 0 || number % 5 == 0 {
            sumOfMult += number
        }
        
        if number % 15 == 0 {
            sumOfMult -= number
        }
    }
    
    return sumOfMult
}

let result = sumOfMultiples()
//print(result)



/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
  1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
//farkli fib algoritmasi
func sumOfEvenFibonacciTerms(upTo limit: Int) -> Int {
    var sum = 0
    var a = 1
    var b = 2
    
    while a <= limit {
        if a % 2 == 0 {
            sum += a
        }
        let nextTerm = a + b
        a = b
        b = nextTerm
    }
    
    return sum
}

// 100e kadar olan fib sayilarini bul
let limit = 100
let summation = sumOfEvenFibonacciTerms(upTo: limit)
//print(summation)



/*
 The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?
 */

func largestPrimeFactor(of number: Int) -> Int {
    var num = number
    var largestPrime = 2
    var factor = 2
    
  //asal sayiyi yakalarken daha hizli nasil bolebiliriz?
    while factor <= num {
        if num % factor == 0 {
            num /= factor
            largestPrime = factor
        } else {
            factor += 1
        }
    }
    
    if num > largestPrime {
        largestPrime = num
    }
    
    return largestPrime
}

let number = 17
let largestPrime = largestPrimeFactor(of: number)
//print("The largest prime factor of \(number) is \(largestPrime)")

